# Production configuration
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: database_psql_user
      POSTGRES_PASSWORD: 'database_pass_123'
      POSTGRES_DB: vouchers-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    hostname: postgres-db

  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-prod
    restart: always
    ports:
      - '3045:3000'
    environment:
      NODE_ENV: production
      PSQL_DB_PORT: 5432
      PSQL_DB_HOST: postgres-db
      PSQL_DB_USER: database_psql_user
      PSQL_DB_PASSWORD: 'database_pass_123'
      PSQL_DB_NAME: vouchers-db
      THROTTLE_TTL: ${THROTTLE_TTL:-1000}
      THROTTLE_LIMIT: ${THROTTLE_LIMIT:-10}
    depends_on:
      - postgres

volumes:
  postgres_data_dev: 